channels:
- conda-forge
dependencies:
- python=3.9.5
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - scikit-learn==1.0.2
  - mlflow==2.5.0
  - holidays==0.17.2
  - flaml==1.2.4
  - category_encoders==2.5.1.post0
  - ray==2.3.1
name: mlflow-env
